# Generated by Django 3.2.9 on 2021-11-14 23:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resinLeft', models.FloatField()),
                ('lastClean', models.DateField()),
                ('resinMount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resinLevel.resin')),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('predictedTime', models.FloatField()),
                ('printerPredictedTime', models.FloatField()),
                ('state', models.IntegerField(choices=[(0, 'standby'), (1, 'success'), (2, 'failure')], default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resinLevel.printer')),
            ],
        ),
    ]
