# Generated by Django 3.2.9 on 2021-11-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resinLevel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resin',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
