# Generated by Django 3.2.9 on 2021-11-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resinLevel', '0002_resin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='predictedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='printerPredictedTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='lastClean',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='resinLeft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='resinMount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resinLevel.resin'),
        ),
    ]
